SELECT a.CAT1,a.PRODNAME,a.PRICE,FINALPRICE,a.CONDITION,a.REF,a.CODE,a.ID,a.TERM,a.DESCRIP FROM (SELECT ROWNUM RN, SALES.* FROM SALES)a 
JOIN (select max(finalPrice), code from auction group by code) USING(CODE) WHERE RN>=1*10-9 AND RN<=1*10;



SELECT a.CAT1,a.PRODNAME,a.PRICE,FINALPRICE,a.CONDITION,a.REF,CODE,a.ID,a.TERM,a.DESCRIP FROM (SELECT ROWNUM RN, SALES.* FROM SALES)a 
JOIN (select max(finalPrice) as FINALPRICE, code from auction group by code) USING(CODE) WHERE RN>=1*10-9 AND RN<=1*10;